export const dataService = [
  {
    key: 1,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 2,
    nameStudent: "Hà Lan",
    testTime: "Tháng 8/2019 - Đợt 1",
    typeTest: "Thi thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "ZIM School of English and Test Preparation",
    source: "Dataweb",
    center: "ZIM – 65 Yên Lãng",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "Xong",
    apmReg: "Chưa đăng kí",
    pkgName: "IELTS Practice Test 1",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Chưa duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Khá",
    pfRollCall: "Có",
  },
  {
    key: 3,
    nameStudent: "Kim Trí Tú",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "Xong",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 1",
    pkgDiscount: "0",
    pgkPayment: "Chưa thanh toán",
    tel: "09091234",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Nha Trang",
    email: "abc@gmail.com",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Xuất phiếu chi hoàn tiền",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Chưa soạn hợp đồng",
    pfSubject: "Listening",
    pfRank: "Khá",
    pfRollCall: "Không",
  },
  {
    key: 4,
    nameStudent: "Park Chaeyoung",
    testTime: "Tháng 8/2019 - Đợt 1",
    typeTest: "Thi thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "ZIM School of English and Test Preparation",
    source: "Dataweb",
    center: "ZIM – 65 Yên Lãng",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmStatus: "Xong",
    apmReg: "Chưa đăng kí",
    pkgName: "IELTS Practice Test 1",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    email: "abc@gmail.com",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Hoàn tiền lớp GR, lập phiếu thu mới cho lớp Foundation",
    fnReward: "Tài trợ thi lại",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Writing",
    pfRank: "Trung Bình",
    pfRollCall: "Không",
  },
  {
    key: 5,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 6,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 7,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 8,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 9,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 10,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 11,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 12,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 13,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 14,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 15,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 16,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 17,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 18,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 19,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 20,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
  {
    key: 21,
    nameStudent: "Nguyễn Lâm Thảo Tâm",
    testTime: "Thi Thử",
    testCost: "200.000",
    testDate: "18/06/2020",
    regDate: "15/06/2020 17:20",
    typeTest: "Thi thử",
    service: "Đăng ký thi IELTS tại BC hoặc IDP",
    cost: "4.500.000",
    provider: "British Council",
    source: "Fanpage",
    center: "ZIM – 12 Huỳnh Lan Khanh",
    apmConsultant: "Lương Ngọc Hoàng Dung",
    apmDate: "09/03/2021",
    apmTime: "09:00",
    apmDone: "",
    apmReg: "Đã đăng kí",
    pkgName: "IELTS Practice Test 2",
    pkgDiscount: "0",
    pgkPayment: "Đã thanh toán",
    pkgSkill: "2",
    listening: "6.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "5.0",
    overall: "6.5",
    tel: "09091234",
    rpCourse:
      "[ZIM - 20L5 Thái Hà] - A-IELTS Solo 3 levels, 19/10, 18:30-20:30,",
    rpCreator: "Chu Minh Thùy",
    rpLeader: "	Nguyễn Anh Toàn",
    city: "Hồ Chí Minh",
    fnStatus: "Duyệt",
    fnReason: "[Chuyển lớp: Chuyển lớp đóng tiền thêm]",
    fnReasonPayment: "Đã hoàn tiền cho học viên",
    fnReward: "Trao thưởng đạt đầu ra",
    cntStatus: "Đã có hợp đồng",
    pfSubject: "Speaking",
    pfRank: "Giỏi",
    pfRollCall: "Có",
  },
];
