type IProfile = IBaseApi<{
  id: number;
  FirstName: string;
  LastName: string;
  FullNameUnicode: string;
  FullNameNonUnicode: string;
  DOB: string;
  Gender: number;
  Mobile: string;
  Extension: string;
  Email: string;
  Address: string;
  AreaID: number;
  StatusID: number;
  RoleID: number;
  Avatar: string;
  SourceInformationID: number;
  JobID: number;
  AcademicPurposesID: number;
  PlacementTestID: number;
  Enable: boolean;
  Role: number;
}>;
