type IWarning = IBaseApi<{
    ID: number,
    BranchID: number,
    BranchName: string,
    CourseID: number,
    CourseName: string,
    UserInformationID: number,
    FullNameUnicode: string,
    Warning: boolean,
    Examresult: string,
    CourseOfStudentPriceID: number,
    Commitment: string,
    Note: string,
    WarningNote: string,
    WarningTeacherID: number,
    WarningTeacherName: string,
    Combo: boolean,
    CreatedBy: string,
    CreatedOn: string,
    ModifiedBy: string,
    ModifiedOn: string
}>