import { Briefcase } from "react-feather";
import React, { Fragment } from "react";

export const dataMenu = [
  {
    MenuName: "tab-home",
    MenuTitle: "Dashboard",
    MenuKey: "/dashboard",
    MenuItem: [
      {
        TypeItem: "single",
        Key: "/dashboard",
        Route: "/dashboard",
        Icon: "",
        Text: "Trang chủ",
      },
    ],
  },
  {
    MenuName: "tab-course",
    MenuTitle: "Khóa học",
    MenuKey: "/course",
    MenuItem: [
      {
        ItemType: "sub-menu",
        Key: "sub-course",
        Icon: '<span class="anticon"><img src="/images/icons/study-course.svg" ></span>',
        TitleSub: "Quản lí khóa học",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/course/create-course",
            Route: "/course/create-course",
            Text: "Tạo khóa học",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/course/create-course-self",
            Route: "/course/create-course-self",
            Text: "Tạo khóa tự học",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/course/course-list",
            Route: "/course/course-list",
            Text: "Danh sách khóa học",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/course/course-list-self",
            Route: "/course/course-list-self",
            Text: "Danh sách khóa tự học",
            Icon: "",
          },
        ],
      },
      {
        TypeItem: "single",
        Key: "/course/schedule-study",
        Icon: '<span class="anticon"><img src="/images/icons/calendar.svg"></span>',
        Route: "/course/schedule-study",
        Text: "Kiểm tra lịch học",
      },
      {
        TypeItem: "single",
        Key: "/course/course-list-report",
        Icon: '<span class="anticon"><img src="/images/icons/list.svg"></span>',
        Route: "/course/course-list-report",
        Text: "Danh sách khóa học - báo cáo",
      },
      {
        TypeItem: "single",
        Key: "/course/course-buy",
        Icon: '<span class="anticon"><img src="/images/icons/list.svg"></span>',
        Route: "/course/course-buy",
        Text: "Danh sách khóa học - mua bán",
      },
    ],
  },

  {
    MenuName: "tab-customer",
    MenuTitle: "Khách hàng",
    MenuKey: "/customer",
    MenuItem: [
      {
        ItemType: "sub-menu",
        Key: "sub-list-course-child",
        Icon: '<span class="anticon"><img src="/images/icons/users.svg"></span>',
        TitleSub: "Học viên",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/student/student-list",
            Route: "/customer/student/student-list",
            Text: "Dữ liệu học viên",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/exchange-student",
            Route: "/customer/student/exchange-student",
            Text: "Học viên chuyển giao",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/student-course",
            Route: "/customer/student/student-course",
            Text: "HV trong khóa",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/student-change-course",
            Route: "/customer/student/student-change-course",
            Text: "HV chuyển khóa",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/student-appointment",
            Route: "/customer/student/student-appointment",
            Text: "HV hẹn đăng ký",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/student-reserve",
            Route: "/customer/student/student-reserve",
            Text: "HV bảo lưu",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/student/student-advisory",
            Route: "/customer/student/student-advisory",
            Text: "HV cần tư vấn",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-parants",
        Icon: '<span class="anticon"><img src="/images/icons/users.svg"></span>',
        TitleSub: "Phụ Huynh",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/parents",
            Route: "/customer/parents",
            Text: "Danh sách phụ huynh",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-course-child-2",
        Icon: '<span class="anticon"><img src="/images/icons/info.svg"></span>',
        TitleSub: "Thi, hẹn test và dịch vụ",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/service/service-customer",
            Route: "/customer/service/service-customer",
            Text: "Khách mua dịch vụ",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/service/service-customer-exam",
            Route: "/customer/service/service-customer-exam",
            Text: "Danh sách đăng kí thi",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/service/service-info-student",
            Route: "/customer/service/service-info-student",
            Text: "Thêm lịch hẹn test",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/service/service-appointment-test",
            Route: "/customer/service/service-appointment-test",
            Text: "Danh sách khách hẹn test",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/service/service-package-customer",
            Route: "/customer/service/service-package-customer",
            Text: "Danh sách khách mua gói",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/service/service-package-result",
            Route: "/customer/service/service-package-result",
            Text: "Danh sách kết quả test",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-course-child-3",
        Icon: '<span class="anticon"><img src="/images/icons/user.svg"></span>',
        TitleSub: "Báo cáo học viên",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/report/report-customer-warning",
            Route: "/customer/report/report-customer-warning",
            Text: "Cảnh báo học viên",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/report/report-customer-test",
            Route: "/customer/report/report-customer-test",
            Text: "Học viên sắp thi",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/report/report-customer-result",
            Route: "/customer/report/report-customer-result",
            Text: "Kết quả thi thực tế",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-course-child-4",
        Icon: '<span class="anticon"><img src="/images/icons/dollar-sign.svg"></span>',
        TitleSub: "Tài chính",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/finance/finance-customer-debts",
            Route: "/customer/finance/finance-customer-debts",
            Text: "Nợ học phí",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/finance/finance-cashier-refund",
            Route: "/customer/finance/finance-cashier-refund",
            Text: "Yêu cầu hoàn tiền",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/finance/finance-cashier-payment",
            Route: "/customer/finance/finance-cashier-payment",
            Text: "Phiếu chi",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/finance/finance-customer-reward",
            Route: "/customer/finance/finance-customer-reward",
            Text: "Thưởng/Tài trợ",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-course-child-5",
        Icon: '<span class="anticon"><img src="/images/icons/clipboard.svg"></span>',
        TitleSub: "Hợp đồng",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/customer/contract/contract-customer-list",
            Route: "/customer/contract/contract-customer-list",
            Text: "Học viên có hợp đồng",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/customer/contract/contract-customer-censorship",
            Route: "/customer/contract/contract-customer-censorship",
            Text: "Duyệt hợp đồng",
            Icon: "",
          },
        ],
      },
    ],
  },

  {
    MenuName: "tab-document",
    MenuTitle: "Document List",
    MenuKey: "/document-list",
    MenuItem: [
      {
        ItemType: "single",
        Key: "/document-list",
        Route: "/document-list",
        Text: "Danh sách tài liệu",
        Icon: "",
      },
    ],
  },
  {
    MenuName: "tab-staff",
    MenuTitle: "Quản lí nhân viên",
    MenuKey: "/staff",
    MenuItem: [
      {
        ItemType: "sub-menu",
        Key: "sub-list-staff-child-1",
        Icon: "",
        TitleSub: "Nhân viên",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/staff/staff-list",
            Route: "/staff/staff-list",
            Text: "Danh sách nhân viên",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/saler-list",
            Route: "/staff/saler-list",
            Text: "Danh sách Salers",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/feedback-list",
            Route: "/staff/feedback-list",
            Text: "Duyệt feedback",
            Icon: "",
          },
        ],
      },
      {
        ItemType: "sub-menu",
        Key: "sub-list-staff-child-2",
        Icon: "",
        TitleSub: "Giáo viên",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/staff/teacher-list",
            Route: "/staff/teacher-list",
            Text: "Giáo viên",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/exercise-done-list",
            Route: "/staff/exercise-done-list",
            Text: "Bài đã chấm",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/exercise-check-list",
            Route: "/staff/exercise-check-list",
            Text: "Duyệt bài",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/teach-hours-list",
            Route: "/staff/teach-hours-list",
            Text: "Giờ dạy giáo viên",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/teach-hours-center",
            Route: "/staff/teach-hours-center",
            Text: "Giờ dạy GV theo trung tâm",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/cost-list",
            Route: "/staff/cost-list",
            Text: "Giá vốn hàng bán",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/teacher-salary-list",
            Route: "/staff/teacher-salary-list",
            Text: "Chi phí lương giáo viên",
            Icon: "",
          },
          // add more
        ],
      },

      {
        ItemType: "sub-menu",
        Key: "sub-list-staff-child-3",
        Icon: "",
        TitleSub: "Lương Office",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/staff/campaign-sales",
            Route: "/staff/campaign-sales",
            Text: "Chiến dịch sale",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/salary-review",
            Route: "/staff/salary-review",
            Text: "Duyệt lương office",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/salary-history",
            Route: "/staff/salary-history",
            Text: "Lịch sử duyệt",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/staff/campaign-revenue",
            Route: "/staff/campaign-revenue",
            Text: "Doanh thu chiến dịch sale",
            Icon: "",
          },
        ],
      },
    ],
  },
  {
    MenuName: "tab-package",
    MenuTitle: "Gói bài tập",
    MenuKey: "/package",
    MenuItem: [
      {
        ItemType: "single",
        Key: "/package/package-list",
        Route: "/package/package-list",
        Text: "Quản lí gói bài",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/package/package-create",
        Route: "/package/package-create",
        Text: "Tạo gói mới",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/package/topic-list",
        Route: "/package/topic-list",
        Text: "Topic",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/package/examiner-list",
        Route: "/package/examiner-list",
        Text: "Danh sách chấm gói bài",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/package/package-set",
        Route: "/package/package-set",
        Text: "Bộ sưu tập",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/package/package-store",
        Route: "/package/package-store",
        Text: "Cửa hàng",
        Icon: "",
      },
    ],
  },
  {
    MenuName: "tab-question-bank",
    MenuTitle: "Ngân hàng đề thi",
    MenuKey: "/question-bank",
    MenuItem: [
      {
        ItemType: "single",
        Key: "/question-bank/question-create",
        Route: "/question-bank/question-create",
        Text: "Tạo câu hỏi & trả lời",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/question-bank/exam-create",
        Route: "/question-bank/exam-create",
        Text: "Tạo đề thi",
        Icon: "",
      },
    ],
  },
  {
    MenuName: "tab-option",
    MenuTitle: "Cấu hình",
    MenuKey: "/option",
    MenuItem: [
      {
        ItemType: "single",
        Key: "/option/center",
        Route: "/option/center",
        Text: "Trung tâm",
      },
      {
        ItemType: "single",
        Key: "/option/grade",
        Route: "/option/grade",
        Text: "Khối học",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/class",
        Route: "/option/class",
        Text: "Lớp học",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/study-time",
        Route: "/option/study-time",
        Text: "Ca học",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/program",
        Route: "/option/program",
        Text: "Chương trình",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/provincial",
        Route: "/option/provincial",
        Text: "Tỉnh/Tp",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/district",
        Route: "/option/district",
        Text: "Quận huyện",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/discount",
        Route: "/option/discount",
        Text: "Mã khuyến mãi",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/customer-supplier",
        Route: "/option/customer-supplier",
        Text: "Nguồn khách hàng",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/day-off",
        Route: "/option/day-off",
        Text: "Ngày nghỉ",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/jobs",
        Route: "/option/jobs",
        Text: "Nghề nghiệp",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/services",
        Route: "/option/services",
        Text: "Dịch vụ",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/feedback",
        Route: "/option/feedback",
        Text: "Loại phản hồi",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/supplier",
        Route: "/option/supplier",
        Text: "Nhà cung cấp",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/purpose",
        Route: "/option/purpose",
        Text: "Mục đích học",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/staff-salary",
        Route: "/option/staff-salary",
        Text: "Lương office",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/teacher-salary",
        Route: "/option/teacher-salary",
        Text: "Lương giáo viên",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/exam",
        Route: "/option/exam",
        Text: "Đợt thi",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/post",
        Route: "/option/post",
        Text: "Kiểm duyệt bài viết",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/info-form",
        Route: "/option/info-form",
        Text: "Form thông tin",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/notification",
        Route: "/option/notification",
        Text: "Tạo thông báo",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/idiom",
        Route: "/option/idiom",
        Text: "Thành ngữ lịch",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/contract",
        Route: "/option/contract",
        Text: "Hợp đồng",
        Icon: "",
      },
      {
        ItemType: "single",
        Key: "/option/term-of-service",
        Route: "/option/term-of-service",
        Text: "Điều khoản",
        Icon: "",
      },
    ],
  },
  {
    MenuName: "tab-layout",
    MenuTitle: "Giao diện",
    MenuKey: "/layoutBase",
    MenuItem: [
      {
        ItemType: "sub-menu",
        Key: "sublayout",
        Icon: "",
        TitleSub: "Layout",
        SubMenuList: [
          {
            ItemType: "single",
            Key: "/layoutBase/layoutTables",
            Route: "/layoutBase/layoutTables",
            Text: "Tables",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/layoutBase/layoutButtons",
            Route: "/layoutBase/layoutButtons",
            Text: "Buttons",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/layoutBase/layoutForms",
            Route: "/layoutBase/layoutForms",
            Text: "Forms",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/layoutBase/layoutCharts",
            Route: "/layoutBase/layoutCharts",
            Text: "Charts",
            Icon: "",
          },
          {
            ItemType: "single",
            Key: "/layoutBase/layoutTags",
            Route: "/layoutBase/layoutTags",
            Text: "Tags",
            Icon: "",
          },
        ],
      },
    ],
  },
];
